#!/bin/bash
# Usage: process (Maybe change network and/or title)

trap "mv omnetpp.ini.orig omnetpp.ini; echo omnetpp.ini restored; exit" SIGHUP SIGINT SIGTERM

if ! type "beep" &> /dev/null; then
  echo "WARNING: For convenience install beep"
fi

network="SG_MULTIHOPMANUAL_001"

cp omnetpp.ini omnetpp.ini.orig

echo "Simulation single dc"
cp omnetpp.ini.dc omnetpp.ini
title="$network-single_dc"
echo "$title"
rm results/*
./run
./process-results "$title"
echo

for i in `seq 0 9`; do
  echo "Simulation single node[$i]"
  cp omnetpp.ini.node$i omnetpp.ini
  title="$network-single_node[$i]"
  echo "$title"
  rm results/*
  ./run
  ./process-results "$title"
  echo
done

cp omnetpp.ini.orig omnetpp.ini
for i in `seq 1 11`; do
  echo "Simulation $i"
  numPingApps="**.backend.numPingApps = $i"
  sed -i '/^**.backend.numPingApps = /c\'"$numPingApps" omnetpp.ini > /dev/null
  title="$network-$(grep numPingApps omnetpp.ini | grep -v ^# | sed 's/**.backend.//' | sed 's/ = /_/')"
  echo "$title"
  rm results/*
  ./run
  ./process-results "$title"
  echo
done

mv omnetpp.ini.orig omnetpp.ini

beep