//
// Generated file, do not edit! Created by opp_msgc 4.3 from applications/udpapp/PaserTrafficDataMsg.msg.
//

#ifndef _PASERTRAFFICDATAMSG_M_H_
#define _PASERTRAFFICDATAMSG_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API 
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API 
#  endif
#endif



/**
 * Class generated from <tt>applications/udpapp/PaserTrafficDataMsg.msg</tt> by opp_msgc.
 * <pre>
 * packet PaserTrafficDataMsg {
 *     string srcId;
 *     int counter;
 *     int hops;
 *     double timestamp;
 * }
 * </pre>
 */
class INET_API PaserTrafficDataMsg : public ::cPacket
{
  protected:
    opp_string srcId_var;
    int counter_var;
    int hops_var;
    double timestamp_var;

  private:
    void copy(const PaserTrafficDataMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PaserTrafficDataMsg&);

  public:
    PaserTrafficDataMsg(const char *name=NULL, int kind=0);
    PaserTrafficDataMsg(const PaserTrafficDataMsg& other);
    virtual ~PaserTrafficDataMsg();
    PaserTrafficDataMsg& operator=(const PaserTrafficDataMsg& other);
    virtual PaserTrafficDataMsg *dup() const {return new PaserTrafficDataMsg(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getSrcId() const;
    virtual void setSrcId(const char * srcId);
    virtual int getCounter() const;
    virtual void setCounter(int counter);
    virtual int getHops() const;
    virtual void setHops(int hops);
    virtual double getTimestamp() const;
    virtual void setTimestamp(double timestamp);
};

inline void doPacking(cCommBuffer *b, PaserTrafficDataMsg& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, PaserTrafficDataMsg& obj) {obj.parsimUnpack(b);}


#endif // _PASERTRAFFICDATAMSG_M_H_
