//
// Generated file, do not edit! Created by opp_msgc 4.3 from applications/udpapp/UDPVideoData.msg.
//

#ifndef _UDPVIDEODATA_M_H_
#define _UDPVIDEODATA_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API 
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API 
#  endif
#endif

// cplusplus {{
#include "INETDefs.h"
// }}



/**
 * Class generated from <tt>applications/udpapp/UDPVideoData.msg</tt> by opp_msgc.
 * <pre>
 * packet UDPVideoDataPacket
 * {
 *     long videoSize = 0;           
 *     long bytesLeft = 0;           
 *     long numPkSent = 0;           
 * }
 * </pre>
 */
class INET_API UDPVideoDataPacket : public ::cPacket
{
  protected:
    long videoSize_var;
    long bytesLeft_var;
    long numPkSent_var;

  private:
    void copy(const UDPVideoDataPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const UDPVideoDataPacket&);

  public:
    UDPVideoDataPacket(const char *name=NULL, int kind=0);
    UDPVideoDataPacket(const UDPVideoDataPacket& other);
    virtual ~UDPVideoDataPacket();
    UDPVideoDataPacket& operator=(const UDPVideoDataPacket& other);
    virtual UDPVideoDataPacket *dup() const {return new UDPVideoDataPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual long getVideoSize() const;
    virtual void setVideoSize(long videoSize);
    virtual long getBytesLeft() const;
    virtual void setBytesLeft(long bytesLeft);
    virtual long getNumPkSent() const;
    virtual void setNumPkSent(long numPkSent);
};

inline void doPacking(cCommBuffer *b, UDPVideoDataPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, UDPVideoDataPacket& obj) {obj.parsimUnpack(b);}


#endif // _UDPVIDEODATA_M_H_
