//
// Generated file, do not edit! Created by opp_msgc 4.3 from applications/udpapp/VideoPacket.msg.
//

#ifndef _VIDEOPACKET_M_H_
#define _VIDEOPACKET_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API 
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API 
#  endif
#endif



/**
 * Class generated from <tt>applications/udpapp/VideoPacket.msg</tt> by opp_msgc.
 * <pre>
 * packet VideoPacket {
 *     unsigned int seqNum;
 *     char type;
 *     unsigned long frameSize;
 * }
 * </pre>
 */
class INET_API VideoPacket : public ::cPacket
{
  protected:
    unsigned int seqNum_var;
    char type_var;
    unsigned long frameSize_var;

  private:
    void copy(const VideoPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const VideoPacket&);

  public:
    VideoPacket(const char *name=NULL, int kind=0);
    VideoPacket(const VideoPacket& other);
    virtual ~VideoPacket();
    VideoPacket& operator=(const VideoPacket& other);
    virtual VideoPacket *dup() const {return new VideoPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned int getSeqNum() const;
    virtual void setSeqNum(unsigned int seqNum);
    virtual char getType() const;
    virtual void setType(char type);
    virtual unsigned long getFrameSize() const;
    virtual void setFrameSize(unsigned long frameSize);
};

inline void doPacking(cCommBuffer *b, VideoPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, VideoPacket& obj) {obj.parsimUnpack(b);}


#endif // _VIDEOPACKET_M_H_
