//
// Generated file, do not edit! Created by opp_msgc 4.3 from networklayer/ipv6/_6lowpan/_6lowpanDatagram.msg.
//

#ifndef __6LOWPANDATAGRAM_M_H_
#define __6LOWPANDATAGRAM_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API 
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API 
#  endif
#endif



/**
 * Class generated from <tt>networklayer/ipv6/_6lowpan/_6lowpanDatagram.msg</tt> by opp_msgc.
 * <pre>
 * packet _6lowpanDatagram {
 *     short transportMessageKind;
 *     unsigned char payload[];
 * }
 * </pre>
 */
class INET_API _6lowpanDatagram : public ::cPacket
{
  protected:
    short transportMessageKind_var;
    unsigned char *payload_var; // array ptr
    unsigned int payload_arraysize;

  private:
    void copy(const _6lowpanDatagram& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const _6lowpanDatagram&);

  public:
    _6lowpanDatagram(const char *name=NULL, int kind=0);
    _6lowpanDatagram(const _6lowpanDatagram& other);
    virtual ~_6lowpanDatagram();
    _6lowpanDatagram& operator=(const _6lowpanDatagram& other);
    virtual _6lowpanDatagram *dup() const {return new _6lowpanDatagram(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual short getTransportMessageKind() const;
    virtual void setTransportMessageKind(short transportMessageKind);
    virtual void setPayloadArraySize(unsigned int size);
    virtual unsigned int getPayloadArraySize() const;
    virtual unsigned char getPayload(unsigned int k) const;
    virtual void setPayload(unsigned int k, unsigned char payload);
};

inline void doPacking(cCommBuffer *b, _6lowpanDatagram& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, _6lowpanDatagram& obj) {obj.parsimUnpack(b);}


#endif // __6LOWPANDATAGRAM_M_H_
